# Dependencies
highlighter: pygments

# Setup
title: Giulio Canti's Blog
url: http://gcanti.github.io
author:
 name: Giulio Canti
 url: http://gcanti.github.io
 email: giulio.canti@gmail.com
 emailHtml: "<a href='mailto:giulio.canti@gmail.com'>giulio.canti@gmail.com</a>"
baseurl: /
about: "<a href='/about.html'>about me</a>"
blog: "<a href='/'>blog</a>"
projects_list:
 - tcomb
projects:
 tcomb:
  name: tcomb
  link: https://github.com/gcanti/tcomb
  markdown: "[tcomb.js](https://github.com/gcanti/tcomb)"
  description: "<a href='https://github.com/gcanti/tcomb'>tcomb.js</a> is a library for Node.js and the browser which allows you to check the types of JavaScript values at runtime."