# Dependencies
highlighter: pygments

# Setup
author: Giulio Canti
baseurl: /
about: "<a href='/about.html'>about me</a>"
blog: "<a href='/'>blog</a>"
email: "<a href='mailto:giulio.canti@gmail.com'>giulio.canti@gmail.com</a>"
projects_list:
 - tcomb
projects:
 tcomb:
  name: tcomb
  link: https://github.com/gcanti/tcomb
  markdown: "[tcomb.js](https://github.com/gcanti/tcomb)"
  description: "<a href='https://github.com/gcanti/tcomb'>tcomb.js</a> is a library for Node.js and the browser which allows you to check the types of JavaScript values at runtime."