# Dependencies
highlighter: pygments
markdown: redcarpet

# Setup
title: Giulio Canti's Blog
url: http://gcanti.github.io
author:
 name: Giulio Canti
 url: http://gcanti.github.io
 email: giulio.canti@gmail.com
 emailHtml: "<a href='mailto:giulio.canti@gmail.com'>giulio.canti@gmail.com</a>"
baseurl: /
about: "<a href='/about.html'>about me</a>"
blog: "<a href='/'>blog</a>"
projects_list:
 - tcomb
 - tcomb-validation
 - tcomb-form
 - tcomb-react
 - tcomb-react-bootstrap
projects:
 tcomb-form:
  name: tcomb-form
  link: https://github.com/gcanti/tcomb-form
  markdown: "[tcomb](https://github.com/gcanti/tcomb-form)"
  description: "<b>Domain Driven Forms</b>. Automatically generate form markup from a domain model. It seems like magic. Check out the <a href='/resources/tcomb-form/playground/playground.html'>Playground</a>."
 tcomb:
  name: tcomb
  link: https://github.com/gcanti/tcomb
  markdown: "[tcomb](https://github.com/gcanti/tcomb)"
  description: "Pragmatic runtime type checking for JavaScript."
 tcomb-react:
  name: tcomb-react
  link: https://github.com/gcanti/tcomb-react
  markdown: "[tcomb-react](https://github.com/gcanti/tcomb-react)"
  description: "Type checking for React components."
 tcomb-react-bootstrap:
  name: tcomb-react-bootstrap
  link: https://github.com/gcanti/tcomb-react-bootstrap
  markdown: "[tcomb-react-bootstrap](https://github.com/gcanti/tcomb-react-bootstrap)"
  description: "Type checking for <a href='https://github.com/react-bootstrap/react-bootstrap'>react-bootstrap</a>. Check out the <a href='/resources/tcomb-react-bootstrap/playground/playground.html'>Playground</a>."
 tcomb-validation:
  name: tcomb-validation
  link: https://github.com/gcanti/tcomb-validation
  markdown: "[tcomb-validation](https://github.com/gcanti/tcomb-validation)"
  description: "A general purpose JavaScript validation library based on type combinators. Check out the <a href='/resources/tcomb-validation/playground/playground.html'>Playground</a>."
