# Dependencies
highlighter: pygments
markdown: redcarpet

# Setup
title: Giulio Canti's Blog
url: http://gcanti.github.io
author:
 name: Giulio Canti
 url: http://gcanti.github.io
 email: giulio.canti@gmail.com
 emailHtml: "<a href='mailto:giulio.canti@gmail.com'>giulio.canti@gmail.com</a>"
baseurl: /
about: "<a href='/about.html'>about me</a>"
blog: "<a href='/'>blog</a>"
projects_list:
 - tcomb-form
 - tcomb
 - tcomb-validation
projects:
 tcomb-form:
  name: tcomb-form
  link: https://gcanti.github.io/tcomb-form
  markdown: "[tcomb-form](https://gcanti.github.io/tcomb-form)"
  description: "React.js powered UI library for developing forms writing less code."
 tcomb:
  name: tcomb
  link: https://gcanti.github.io/tcomb
  markdown: "[tcomb](https://gcanti.github.io/tcomb)"
  description: "Pragmatic runtime type checking for JavaScript based on set theory."
 tcomb-validation:
  name: tcomb-validation
  link: https://github.com/gcanti/tcomb-validation
  markdown: "[tcomb-validation](https://github.com/gcanti/tcomb-validation)"
  description: "A general purpose JavaScript validation library based on type combinators. Check out the <a href='/resources/tcomb-validation/playground/playground.html'>Playground</a>."
